-- MySQL Script generated by MySQL Workbench
-- Mon May 15 20:12:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
/*insert into Users(firstName, lastName, email, password) 
values ('Mladen', 'Lazic', 'mladen.lazic93@hotmail.com', 'dajsifru1'), 
	   ('Nikola', 'Lazic', 'nikola@hotmail.com', '11111111')*/
	   
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id1660589_vrpbase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id1660589_vrpbase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id1660589_vrpbase` DEFAULT CHARACTER SET utf8 ;
USE `id1660589_vrpbase` ;

-- -----------------------------------------------------
-- Table `id1660589_vrpbase`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id1660589_vrpbase`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
